-- Migration 040: Add display_name column to packages table
-- Description: Adds optional display name for better SEO and human-readable titles
-- Author: AI Assistant
-- Date: 2025-01-09

-- Add display_name column to packages table
ALTER TABLE packages ADD COLUMN IF NOT EXISTS display_name TEXT;

-- Add index for searching by display name
CREATE INDEX IF NOT EXISTS idx_packages_display_name ON packages(display_name) WHERE display_name IS NOT NULL;

-- Add comment
COMMENT ON COLUMN packages.display_name IS 'Human-readable display name for the package (e.g., "React TypeScript Rules"). Used as page title and main heading on SEO pages. If not provided in prpm.json, it will be auto-generated by AI during publish.';

-- Note: Existing packages will have display_name generated on next publish or can be backfilled
